name: surreact_env

channels:
  - pytorch
  - conda-forge

dependencies:
  - pip
  - opencv
  - python
  - matplotlib
  - numpy
  - cudatoolkit=10.1
  - pytorch
  - scipy
  - ffmpeg
  - pillow
  - mock